### ISSUE TITLE
Jackett fails to initialize PersistentVolume

### ISSUE THREAD

**Issue by corco** [k8s-at-home/container-images#51]
Installing a fresh jackett helm install (using k8s-at-home chart) fails.

This is the value files I used:

```yaml
  image:
     repository: ghcr.io/k8s-at-home/jackett
     tag: v0.17.656   
  persistence:    
    config:    
      enabled: true    
      storageClass: "longhorn"    
      accessMode: ReadWriteOnce    
      size: "1Gi"
```

And the command `helm install jackett k8s-at-home/jackett --values values.yaml`

I get the following error:

```
03-08 19:24:53 Info Starting Jackett v0.17.656 
Unhandled exception. System.Exception: Could not create settings directory. Access to the path '/config/Jackett' is denied.
   at Jackett.Common.Services.ConfigurationService.CreateOrMigrateSettings() in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 52
   at Jackett.Server.Program.Main(String[] args) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 77
```

I believe the issue is that jackett starts with a user different than root, while the volume is accessible only by root.

There is no problem if persistence is disabled, i.e. using the default volume provided.

There is also no issue if I install the helm chart with the linuxserver/jackett, and then upgrade the chart to use ghcr.io/k8s-at-home/jackett, which I assume is that their container initialize the volume as root before starting jackett.

**Comment by onedr0p** [comment]
Hi! Did you read the docs on permissions? There are a few different things you can do to fix this issue and they are all documented at

https://docs.k8s-at-home.com/our-container-images/permissions/

**Comment by onedr0p** [comment]
This is not an issue with my backing storage which is rook-ceph. Longhorn must handle permissions differently.
