### ISSUE TITLE
[sabnzbd] 3.x doesn't work with IPv6 disabled on host system

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#7]
```
Fatal error:
  Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.
```

Also see this LSIO issue https://github.com/linuxserver/docker-sabnzbd/issues/82

**Comment by carpenike** [comment]
don't disable ipv6. :)

**Comment by nemchik** [comment]
I believe I'm experiencing this issue as well. I'm using a VPS that does not (to my knowledge) support ipv6. Here is the relevant section I found in the docker container logs:
```
2020-11-16 18:50:41,652::INFO::[SABnzbd:1427] Starting web-interface on 0.0.0.0:8080
2020-11-16 18:50:41,653::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Bus STARTING
2020-11-16 18:50:41,759::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Serving on http://172.20.0.10:8080
2020-11-16 18:50:41,763::ERROR::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
self.httpserver.start()
File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1813, in start
self.prepare()
File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1772, in prepare
raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 8080): [Errno 98] Address already in use)
2020-11-16 18:50:41,764::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Bus STOPPING
2020-11-16 18:50:41,766::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('172.20.0.10', 8080)) shut down
2020-11-16 18:50:41,767::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) already shut down
2020-11-16 18:50:41,767::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Bus STOPPED
2020-11-16 18:50:41,767::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Bus EXITING
2020-11-16 18:50:41,768::INFO::[_cplogging:216] [16/Nov/2020:18:50:41] ENGINE Bus EXITED
```
