### ISSUE TITLE
[zenbot] fix build

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#73]
# Details

**Image name:**

zenbot

**Additional Information:**

Broken build

**Comment by onedr0p** [comment]
@anthr76 this one is for you

**Comment by onedr0p** [comment]
https://github.com/k8s-at-home/container-images/runs/2153219194?check_suite_focus=true

```#11 1041.5 gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
#11 1041.6 make: Entering directory '/app/node_modules/node-sass/build'
#11 1041.6   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/10.19.0/include/node -I/root/.node-gyp/10.19.0/src -I/root/.node-gyp/10.19.0/deps/openssl/config -I/root/.node-gyp/10.19.0/deps/openssl/openssl/include -I/root/.node-gyp/10.19.0/deps/uv/include -I/root/.node-gyp/10.19.0/deps/zlib -I/root/.node-gyp/10.19.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -fPIC -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
#11 1042.3 In file included from ../src/binding.cpp:3:
#11 1042.3 ../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
#11 1042.3     8 | #include <sass/context.h>
#11 1042.3       |          ^~~~~~~~~~~~~~~~
#11 1042.3 compilation terminated.
#11 1042.3 make: *** [binding.target.mk:116: Release/obj.target/binding/src/binding.o] Error 1
#11 1042.3 make: Leaving directory '/app/node_modules/node-sass/build'
#11 1042.3 gyp ERR! build error 
#11 1042.4 gyp ERR! stack Error: `make` failed with exit code: 2
#11 1042.4 gyp ERR! stack     at ChildProcess.onExit (/app/node_modules/node-gyp/lib/build.js:262:23)
#11 1042.4 gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
#11 1042.4 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
#11 1042.4 gyp ERR! System Linux 5.4.0-1040-azure
#11 1042.4 gyp ERR! command "/usr/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#11 1042.4 gyp ERR! cwd /app/node_modules/node-sass
#11 1042.4 gyp ERR! node -v v10.19.0
#11 1042.4 gyp ERR! node-gyp -v v3.8.0
#11 1042.4 gyp ERR! not ok 
#11 1042.4 Build failed with error code: 1
#11 1050.9 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#11 1050.9 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#11 1050.9 
#11 1051.0 npm ERR! code ELIFECYCLE
#11 1051.0 npm ERR! errno 1
#11 1051.0 npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
#11 1051.0 npm ERR! Exit status 1
#11 1051.0 npm ERR! 
#11 1051.0 npm ERR! Failed at the node-sass@4.14.1 postinstall script.
#11 1051.0 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#11 1051.7 
#11 1051.7 npm ERR! A complete log of this run can be found in:
#11 1051.7 npm ERR!     /root/.npm/_logs/2021-03-20T01_11_15_325Z-debug.log
#11 ERROR: executor failed running [/bin/bash -o pipefail -c export EXTRA_INSTALL_ARG="node-gyp";   sed -i '/_apt/d' /etc/passwd   &&   apt-get -qq update   &&   apt-get -qq install -y     nodejs     npm     build-essential     git     ${EXTRA_INSTALL_ARG}   &&   curl -fsSL "https://github.com/DeviaVir/zenbot/archive/${VERSION}.tar.gz" | tar xzf - -C /app --strip-components 1   &&   echo "${VERSION}" > /app/version.txt   &&   echo "unstable" > /app/branch.txt   &&   chown -R kah:kah /app   &&   npm install /app --unsafe   &&   apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false   &&   apt-get autoremove -y   &&   apt-get clean   && rm -rf   /app/.github   /app/assets   /app/docs   /app/Dockerfile   /app/docker-compose*   /app/simulations   /app/*.md]: exit code: 1
------
 > [linux/arm64 2/3] RUN   export EXTRA_INSTALL_ARG="node-gyp";   sed -i '/_apt/d' /etc/passwd   &&   apt-get -qq update   &&   apt-get -qq install -y     nodejs     npm     build-essential     git     ${EXTRA_INSTALL_ARG}   &&   curl -fsSL "https://github.com/DeviaVir/zenbot/archive/4.1.2-1646-g8dde2383.tar.gz" | tar xzf - -C /app --strip-components 1   &&   echo "4.1.2-1646-g8dde2383" > /app/version.txt   &&   echo "unstable" > /app/branch.txt   &&   chown -R kah:kah /app   &&   npm install /app --unsafe   &&   apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false   &&   apt-get autoremove -y   &&   apt-get clean   && rm -rf   /app/.github   /app/assets   /app/docs   /app/Dockerfile   /app/docker-compose*   /app/simulations   /app/*.md:
------```

**Comment by anthr76** [comment]
Checking..

**Comment by onedr0p** [comment]
Looks like this could be a thing

https://stackoverflow.com/questions/56195342/node-sass-sass-context-wrapper-h810-fatal-error-sass-context-h-no-such-fi

**Comment by onedr0p** [comment]
removed image at request of @anthr76

**Comment by anthr76** [comment]
👋🏼
